Feat: implement achievements
EdvardPotapenko/pp_bot pull request #11
Opened 2021-08-10 05:42 UTC by EdvardPotapenko

@vova-lantsov-dev
Посмотри пожалуйста и скажу что ты думаешь об этом. Было бы здорово если бы запулил себе локально и тоже потыкал, может найдешь какие-то недоработки. Я сам локально протестил, но вторая пара глаз не помешает.

2021-08-10 06:32 UTC, vova-lantsov-dev requested changes

2021-08-10 06:32 UTC, vova-lantsov-dev commented on src/docker-compose.debug.yml
> +version: '3.8'
Уже в принципе версия 3.9 доступна для использования)

2021-08-10 06:32 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Achievements/EuropeAchievement.cs
> +                _context.Update(userChat);
Поскольку ты не вызвал AsNoTracking, можешь просто Save, без Update

2021-08-10 06:32 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Achievements/IAchievable.cs
> +        Task IsAcquiredAsync(Message m, CancellationToken ct);
Название чуть не логичное, лучше AcquireAsync

2021-08-10 06:32 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Models/BotUserChat.cs
> +        public int LastPPLengthChange { get; set; }
Лучше сделай таблицу, куда записывай КАЖДОЕ изменение каждого юзера, это даст бэкграунд для будущих ачивок. Надо начать пополнять таблицу уже сейчас. Если помнишь, у нас есть целый список задуманных ачивок

2021-08-10 06:32 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Models/BotUserChat.cs
> +        public int LastPPLengthChange { get; set; }
Туда же писать дату изменения, для будущей фильтрации и сортировки

2021-08-10 07:36 UTC, EdvardPotapenko commented
@vova-lantsov-dev Внес запрошенные тобой изменения

2021-08-10 09:56 UTC, EdvardPotapenko commented
> @vova-lantsov-dev Внес запрошенные тобой изменения 

Понял что проверка длинны по истории не работает нормально, пофикшу чуть позже

2021-08-10 10:00 UTC, vova-lantsov-dev requested changes

2021-08-10 10:00 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Models/GrowHistory.cs
> +        public DateTime ExecutionTime{get;init;} = DateTime.Now;
Лучше DateTime.UtcNow

2021-08-10 10:07 UTC, vova-lantsov-dev requested changes

2021-08-10 10:07 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Achievements/IAchievable.cs
> +    {
Добавь в интерфейс следующие свойства

string Name { get; }
string Description { get; }

В каждой реализации будем их задавать и в будущем использовать для отображения результатов в боте

2021-08-10 18:55 UTC, EdvardPotapenko commented on src/pp_bot.Server/Achievements/IAchievable.cs
> +    {
Как это будет связано с данными в базе? В ней тоже есть название и описание, просто мапить их внутри объекта который обрабатывает достижение?

2021-08-10 22:42 UTC, EdvardPotapenko commented
@vova-lantsov-dev Пошел немного другим путем. Оставил названия в базе, так как очень удобно будет из контекста брать списки с названиями для использование в тех же коммандах (ListAchievementsCommand). Вместо того чтобы добавить свойста имени и описания - закешировал объект ачивки  в конструкторе как **readonly** свойство интерфейса (есть проверка на сущестование в базе, если что вылазит NotImplementedException).

2021-08-11 06:13 UTC, vova-lantsov-dev commented
@EdvardPotapenko та ну, замедляешь выполнение же

В конструкторе, получая ачивку из бд, ты:
1) потерял асинхронный контекст
2) нагрузил конструктор
3) отключил возможность оптимизации - зачем сразу вытягивать ачивку из бд, если её условия могут быть не выполнены? Надо её внутри if вытягивать, когда условие прошло

2021-08-11 06:22 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Achievements/TripleAchievement.cs
> +            Achievement = _context.Achievements.FirstOrDefault(a => a.Id == ACHIEVEMENT_ID);
Крч мне не нравится как сделан тут подход, я наверное свою логику залью позже

2021-08-11 06:37 UTC, EdvardPotapenko commented on src/pp_bot.Server/Achievements/TripleAchievement.cs
> +            Achievement = _context.Achievements.FirstOrDefault(a => a.Id == ACHIEVEMENT_ID);
Ладно, тогда не буду тратить время.

2021-08-13 09:35 UTC, EdvardPotapenko commented on src/pp_bot.Server/Achievements/TripleAchievement.cs
> +            Achievement = _context.Achievements.FirstOrDefault(a => a.Id == ACHIEVEMENT_ID);
@vova-lantsov-dev проверь последний коммит как будет время.

2022-03-19 11:12 UTC, merged