created achievements table and relations
EdvardPotapenko/pp_bot pull request #4
Opened 2021-03-30 08:15 UTC by EdvardPotapenko

@vova-lantsov-dev Please check and comment what do you think about this. 

I'm still not sure where we should store achievements initial list (**database** or some kind of **json file** ?) 

Anyway. We can uses this table for both of this, but if we choose to use it as a, basically, DTO object for users achievements and store initial list somewhere else - I think it would be helpful to ad AcquiredDate field to the Achievement class.

And I fixed docker-compose debug config a lil bit.

2021-03-30 08:27 UTC, vova-lantsov-dev requested changes
Кроме нехватающего свойства, нужно создать таблицу с данными, когда и кто выполнил команду `/grow`

Столбцы:
- UserId
- Change
- DateTime

По дате и юзеру сможем потом сортировать, а по Change поймём, ушёл юзер в плюс или в минус.
Без этой таблицы и записи в ней всех изменений многие ачивки будут недоступны для реализации.

2021-03-30 08:27 UTC, vova-lantsov-dev commented on src/pp_bot.Server/Models/Achievement.cs
> +        public List<BotUser> UsersAcquired{get;set;} = new List<BotUser>();
Забыл ещё ImageUrl

2021-07-31 13:39 UTC, EdvardPotapenko commented on src/pp_bot.Server/Models/Achievement.cs
> +        public List<BotUser> UsersAcquired{get;set;} = new List<BotUser>();
Хотел обсудить поле Change. Мне кажется нам не стоит привязываться в таблицах к метрике длинны пользователя, так как не все достижения будут строиться на ней и каждая такая ситуация будет исколючительным кодом с нашей стороны. 

Хотел предложить свое решение на данный момент, которое чем-то схоже с твоими советами но не до конца:
Та же таблица Achievements, добавил поле для название файла картинки. По навигационному свойству UsersAcquired мы сможем вытаскивать, например, количество пользователей которые получили данное достижение.
```
public class Achievement
    {
        public int Id {get;init;}

        public string Name {get;init;}

        public string Description {get;init;}
        
        *public string ImageFileName {get;init;}*
        
        public List<BotUser> UsersAcquired{get;set;} = new List<BotUser>();
    }

```
Добавим в DTO объект свойство для иконки и будем мапить к нему, когда возвращать данные в бот (по сути объект будет идентичным domain объекту, но свойство названия файла картинки замениться на объект, скорее-всего InputOnlineFile, картинки, насколько я помню в Telegram.Bot метод отправки файлов обычно ожидает именно его), т.е. :

```
public class AchievementResponse
    {
        public int Id {get;init;}

        public string Name {get;init;}

        public string Description {get;init;}
        
        *public InputOnlineFile Icon {get;init;}*
        
        public List<BotUser> UsersAcquired{get;set;} = new List<BotUser>();
    }
```
Одним из использований данного класса будет отображение пользователю полученного достижение.

Также немного подправим  BotUserChat:

```
public sealed class BotUserChat
    {
        public int ChatUsersId { get; set; }
        public BotUser User { get; set; }
        public long UserChatsChatId { get; set; }
        public Chat Chat { get; set; }
        public int PPLength { get; set; }
        public DateTime LastManipulationTime { get; set; }
        *public List<Achievement> AcquiredAchievements {get;set;} = new List<Achievement>();*
    }
```
Так достижения пользователя будут привязаны к чату, и будет понятно что он уже получил.

Хорошо, у нас есть таблица с достижениями, логику будем писать так:
Интерфейс IAchievable, который имплементируют все класы достижений - описывает логику выполнения проверки на получение достижения.

```
public interface IAchievable
{
    // Этот метод реализует свою кастомную логику проверки условий на выполнения достижений.
    public Task IsAcquiredAsync(Message m, CancellationToken ct);
}
```

Также допилим DatabaseHelper вот этим методом, так как нам нужно будет записовать полученные ачивки в BotUserChat:

```
public async Task<Chat> GetUserChatAsync(Message message, CancellationToken ct)
{
    return await Context.BotUserChat
                .Include(uc => uc.AcquiredAchievements)
                .FirstOrDefaultAsync
                 (
                     uc => uc.Chat.ChatId == message.Chat.Id && 
                     uc.User.TelegramId == message.From.Id,
                     ct
                 );
}
```

И будет что-то такое в итоге:

```
public class FirstHundredAchievement : IAchievable
    {
        private const int ACHIEVEMENT_ID  = 1;
        private readonly PPContext _context;
        private readonly DatabaseHelper _databaseHelper;
        private readonly ITelegramBotClient _client;
        
        public FirstHundredAchievement(ITelegramBotClient client, PP_Context context, DatabaseHelper databaseHelper)
        {
            _client = client;
            _context = context;
           _databaseHelper = databaseHelper;
        }

        public async Task IsAcquiredAsync(Message m, CancellationToken ct);
        {
            // Я подумал что каждый раз получать свежий объект достижения будет неплохой идеей, но возможно ты знаешь способ получше чтобы его закешировать, скажем в конструкторе, правда не знаю насколько это будет правильно.
            var achievement = await _context.Achievements.FindAsync(ACHIEVEMENT_ID, ct);
            var user = await _databaseHelper.GetUserAsync(m,ct);
            var userChat = await _databaseHelper.GetUserChatAsync(m,ct);

            if(userChat.AcquiredAchievements.Contains(achievement))
                return Task.CompletedTask;

            if(userChat.PPLength >= 100)
            {
                userChat.AcquiredAchievements.Add(achievement);
                achievement.UsersAcquired.Add(user);

                _context.Update(userChat);
                _context.Update(achievement);
                await _context.SaveChangesAsync();
            }
        }
    }
```
Окей, это все конечно весело, но как и когда выполнять проверки на получения достижений?
Хороший вопрос, скорее-всего будем использовать тот же подход что и с сообщениями, т.е. создаем класс AchievementManager, что ты в принципе уже и сделал.

Для того чтобы понять как его реализовать - стоит подумать о том как будет происходить обработка условий на выполнение достижений и когда, и из этого прикинуть сложность данного алгоритма:

Для *каждого пользователя* в *каждом чате* будет выполняться проверка *каждого реализованного достижения*, значит имеем сложность O(n), чем больше будет чатов, пользователей и достижений, тем больше ресурсов и времени будет занимать просчет выполненных достижений для них. Это можно было бы улучшить следующим образом:
Уменьшить выборку чатов или пользователей мы не можем, но вот достижения можем немного оптимизировать.

Если добавить ещё пару интерфейсов, помимо IAchievable: ILengthAchievable, ITransferAchievable, IChatAchievable - то можно разбить проверку условий для достижений в определенных сценариях, так мы будем при выполненни комманды `grow` проверять только достижения связанные с изменением метрики длинны и.т.д. Для того чтобы каждый раз не выполнять отсеивание из общего списка IAchievable - лучше всего в DI сразу создать пару сервисов под каждый тип достижение (схоже с тем, как ты делал с коммандами).

Звучит весело, но пока у нес нет механизма разделения действий которые выполняет пользователь на категории, так как обработка комманд спрятана за абстракцией, и не просто так. Такое распределение я пытался сделать в боте в нашем репозитории [CaffeMenuBot](https://github.com/krok-lives-matter/CaffeMenuBot_Back-End/blob/main/src/CaffeMenuBot.Bot/Services/BotHandler.cs), но пока что забили на данную тему, может когда-то вернемся к ней.

*Пока - просто будем проверять при каждом апдейте от бота наличие выполенения всех реализованных ачивок.*

```
public interface IAchievementManager
{
    public Task HandleAchievementsAsync(Message m, CancellationToken ct);
}
    
public sealed class AchievementManager : IAchievementManager
{
    private readonly IServiceProvider _provider;
    private readonly ILoggerFactory _loggerFactory;

    public AchievementManager(IServiceProvider provider, ILoggerFactory loggerFactory)
    {
        _provider = provider;
        _loggerFactory = loggerFactory;
    }

    public async Task HandleAchievementsAsync(Message m, CancellationToken ct)
    {
        using var scope = _provider.CreateScope();
        var scopedProvider = scope.ServiceProvider;

        IEnumerable<IAchievable> achievements = scopedProvider.GetServices<IAchievable>();
        foreach (var achievement in achievements)
        {
                try
                {
                    await achievement.IsAcquiredAsync(m, ct);
                }
                catch (Exception e)
                {
                    var logger = _loggerFactory.CreateLogger(command.GetType());
                    logger.LogError(e, "Exception occurred while checking achievement");
                }
                break;
            }
        }
    }
}
```

Ну а выполнять сие чудо будем в `BotHanlder`:
```
private async Task HandleMessageAsync(Message m, CancellationToken ct)
{
    await _commandPatternManager.HandleCommandAsync(m, ct);
    await _achievementManager.HandleAchievementsAsync(m, ct);
}
```
Ещё немно [...]

2021-08-10 04:07 UTC, EdvardPotapenko commented on src/pp_bot.Server/Models/Achievement.cs
> +        public List<BotUser> UsersAcquired{get;set;} = new List<BotUser>();
Я понял что ты просил когда упоминал Change, в pull request'е чекнешь когда создам.

2021-08-10 07:49 UTC, closed without merging